window.CTL_DATA = {
  "distritais": [
    "André Navarro",
    "Darci D'Anuncio",
    "Edmarcos Oliveira",
    "Francisco Hermano",
    "Glauco Freire",
    "Marco Antônio Oliveira",
    "Marcos Longas",
    "Rodrigo Frigoni",
    "Rodrigo Longo",
    "Rodrigo Peixoto",
    "Rodrigo Rodrigues",
    "Timótheo Silveira"
  ],
  "tecnicos": [
    "Alexandre Scarpa",
    "Alice Arantes",
    "Bianca Souza",
    "Fábio Fogaça",
    "Felipe Secco",
    "Guilherme Marquez",
    "Gustavo Gonçalves",
    "Itamar Aguiar",
    "Natália Espanhol",
    "Paula Tiveron",
    "Rafael Azevedo",
    "Rayce Ferreira",
    "Reginaldo Santos",
    "Tiago Ferreira"
  ],
  "regionais": [
    "MG JUIZ DE FORA",
    "MG LEOPOLDINA",
    "MG MATIPO",
    "MG RIO CASCA",
    "RJ CAMPOS",
    "RJ RIO DE JANEIRO",
    "SP BATATAIS",
    "SP BOTUCATU",
    "SP BRAGANCA PAULISTA",
    "SP GUARATINGUETA",
    "SP MARILIA",
    "SP PIRACICABA",
    "SP RIBEIRAO PRETO",
    "SP RIO CLARO",
    "SP SAO JOAO DA BOA VISTA",
    "SP SAO JOSE DO RIO PRETO",
    "SP VARGEM GRANDE DO SUL",
    "AC ACRE",
    "MS CAMPO GRANDE",
    "MT ALTA FLORESTA",
    "MT CUIABA SUL",
    "MT SINOP",
    "DF BRASILIA",
    "GO PLANALTO CENTRAL",
    "GO PORANGATU",
    "GO VALE DOURADO",
    "MT COCALINHO",
    "SP ITAPETININGA",
    "TO ARAGUAINA",
    "TO DIANOPOLIS",
    "TO GURUPI",
    "TO TOCANTINS NORTE",
    "TO TOCANTINS SUL",
    "AL MACEIO",
    "CE CEARA",
    "PE RECIFE",
    "BA BARREIRAS",
    "BA EUNAPOLIS",
    "BA FEIRA DE SANTANA",
    "BA GUANAMBI",
    "BA ITABUNA",
    "BA ITAPETINGA",
    "BA OESTE BAHIA",
    "BA SANTA MARIA DA VITORIA",
    "BA TEIXEIRA DE FREITAS",
    "BA VITORIA CONQUISTA",
    "ES ESPIRITO SANTO",
    "ES LINHARES",
    "MG ARACUAI",
    "MG BELO HORIZONTE NORTE",
    "MG CENTRAL DE MINAS",
    "MG GOVERNADOR VALADARES",
    "MG MONTES CLAROS",
    "MG MUCURI",
    "MG NANUQUE",
    "MG POMPEU",
    "MG TEOFILO OTONI",
    "PR BARRACAO",
    "PR CAMPO MOURAO",
    "PR CANDIDO RONDON",
    "PR CORNELIO PROCOPIO",
    "PR GUARAPUAVA",
    "PR MANGUEIRINHA",
    "PR MARINGA",
    "PR NOVA LARANJEIRAS",
    "PR SAO JOAO",
    "RS CACHOEIRA DO SUL",
    "RS DOM PEDRITO",
    "RS PELOTAS",
    "RS PORTO ALEGRE",
    "RS SANTIAGO",
    "SC CAPINZAL",
    "SC SANTA CATARINA CORTE",
    "AM MANAUS",
    "GO VALE DO ARAGUAIA",
    "MA ACAILANDIA",
    "MA IMPERATRIZ",
    "MA PRESIDENTE DUTRA",
    "MA SANTA INES",
    "PA ALTAMIRA",
    "PA BELEM",
    "PA JACUNDA",
    "PA MARABA",
    "PA ORIXIMINA",
    "PA PARAGOMINAS",
    "PA XINGU",
    "PA XINGUARA",
    "PR FRANCISCO BELTRAO",
    "PR LONDRINA",
    "RR RORAIMA",
    "SC MARAVILHA",
    "GO OESTE GOIANO",
    "MT AGUA BOA",
    "MT BARRA DO GARCAS",
    "MT CONFRESA",
    "MT CUIABA",
    "MT JUINA",
    "MT MATUPA",
    "MT NOVA XAVANTINA",
    "MT OESTE MT",
    "MT PONTES E LACERDA",
    "MT RONDONOPOLIS",
    "RO RONDONIA",
    "GO GOIAS SUL",
    "GO IPORA",
    "GO MORRINHOS",
    "GO RIO VERDE",
    "MG ARAGUARI",
    "MG CENTRO OESTE DE MINAS",
    "MG GUIMARANIA",
    "MG ITUIUTABA",
    "MG JOAO PINHEIRO",
    "MG LAGOA FORMOSA",
    "MG PARACATU",
    "MG PATOS DE MINAS",
    "MG PATOS NORTE",
    "MG PERDIZES",
    "MG PONTAL",
    "MG SANTA VITORIA",
    "MG TIROS",
    "MG TRIANGULO",
    "MG UBERABA",
    "MG UBERLANDIA",
    "GO GOIANIA",
    "GO GOIAS NORTE",
    "GO MINEIROS",
    "PA NOVO PROGRESSO",
    "SP ARACATUBA",
    "SP BAURU",
    "Virtual Sales Region",
    "MG BELO HORIZONTE SUL",
    "MG BOM SUCESSO",
    "MG CARMO DO RIO CLARO",
    "MG CONSELHEIRO LAFAIETE",
    "MG ITABIRA",
    "MG ITANHANDU",
    "MG LAVRAS",
    "MG POUSO ALEGRE",
    "MG SAO GONCALO DO SAPUCAI",
    "MG SAO JOAO DEL REI",
    "SE SERGIPE",
    "PR CARAMBEI",
    "PR CASTRO",
    "RS FREDERICO WESTPHALEN",
    "RS IJUI",
    "RS SANTA ROSA",
    "RS TAPEJARA",
    "RS TEUTONIA",
    "SC BRACO DO NORTE",
    "SC CONCORDIA",
    "SC SANTA CATARINA",
    "SC TIMBO",
    "SC TREZE TILIAS"
  ],
  "emailsDistritais": {
    "André Navarro": "Andre.Navarro@altagenetics.com",
    "Darci D'Anuncio": "ddanuncio@altagenetics.com",
    "Edmarcos Oliveira": "Edmarcos.Oliveira@altagenetics.com",
    "Francisco Hermano": "fhermano@altagenetics.com",
    "Glauco Freire": "gfreire@altagenetics.com",
    "Marco Antônio Oliveira": "Marco.Oliveira@altagenetics.com",
    "Marcos Longas": "mlongas@altagenetics.com",
    "Rodrigo Frigoni": "Rodrigo.Frigoni@altagenetics.com",
    "Rodrigo Longo": "rodrigo.longo@altagenetics.com",
    "Rodrigo Peixoto": "rodrigo.peixoto@altagenetics.com",
    "Rodrigo Rodrigues": "rrodrigues@altagenetics.com",
    "Timótheo Silveira": "Timotheo.Silveira@altagenetics.com"
  },
  "emailsTecnicos": {
    "Alexandre Scarpa": "alexandre.scarpa@altagenetics.com",
    "Alice Arantes": "Alice.Arantes@altagenetics.com",
    "Bianca Souza": "bianca.ribeiro@altagenetics.com",
    "Fábio Fogaça": "ffogaca@altagenetics.com",
    "Felipe Secco": "Felipe.Secco@altagenetics.com",
    "Guilherme Marquez": "gmarquez@altagenetics.com",
    "Gustavo Gonçalves": "Gustavo.Goncalves@altagenetics.com",
    "Itamar Aguiar": "itamar.aguiar@altagenetics.com",
    "Natália Espanhol": "nathalia.espanhol@altagenetics.com",
    "Paula Tiveron": "paula.tiveron@altagenetics.com",
    "Rafael Azevedo": "rafael.azevedo@altagenetics.com",
    "Rayce Ferreira": "Rayce.Ferreira@altagenetics.com",
    "Reginaldo Santos": "rsantos@altagenetics.com",
    "Tiago Ferreira": "tiago.ferreira@altagenetics.com"
  },
  "regionalParaDistrital": {
    "MG JUIZ DE FORA": "André Navarro",
    "MG LEOPOLDINA": "André Navarro",
    "MG MATIPO": "André Navarro",
    "MG RIO CASCA": "André Navarro",
    "RJ CAMPOS": "André Navarro",
    "RJ RIO DE JANEIRO": "André Navarro",
    "SP BATATAIS": "André Navarro",
    "SP BOTUCATU": "André Navarro",
    "SP BRAGANCA PAULISTA": "André Navarro",
    "SP GUARATINGUETA": "André Navarro",
    "SP MARILIA": "André Navarro",
    "SP PIRACICABA": "André Navarro",
    "SP RIBEIRAO PRETO": "André Navarro",
    "SP RIO CLARO": "André Navarro",
    "SP SAO JOAO DA BOA VISTA": "André Navarro",
    "SP SAO JOSE DO RIO PRETO": "André Navarro",
    "SP VARGEM GRANDE DO SUL": "André Navarro",
    "AC ACRE": "Darci D'Anuncio",
    "MS CAMPO GRANDE": "Darci D'Anuncio",
    "MT ALTA FLORESTA": "Darci D'Anuncio",
    "MT CUIABA SUL": "Darci D'Anuncio",
    "MT SINOP": "Darci D'Anuncio",
    "DF BRASILIA": "Edmarcos Oliveira",
    "GO PLANALTO CENTRAL": "Edmarcos Oliveira",
    "GO PORANGATU": "Edmarcos Oliveira",
    "GO VALE DOURADO": "Edmarcos Oliveira",
    "MT COCALINHO": "Edmarcos Oliveira",
    "SP ITAPETININGA": "Edmarcos Oliveira",
    "TO ARAGUAINA": "Edmarcos Oliveira",
    "TO DIANOPOLIS": "Edmarcos Oliveira",
    "TO GURUPI": "Edmarcos Oliveira",
    "TO TOCANTINS NORTE": "Edmarcos Oliveira",
    "TO TOCANTINS SUL": "Edmarcos Oliveira",
    "AL MACEIO": "Francisco Hermano",
    "CE CEARA": "Francisco Hermano",
    "PE RECIFE": "Francisco Hermano",
    "BA BARREIRAS": "Glauco Freire",
    "BA EUNAPOLIS": "Glauco Freire",
    "BA FEIRA DE SANTANA": "Glauco Freire",
    "BA GUANAMBI": "Glauco Freire",
    "BA ITABUNA": "Glauco Freire",
    "BA ITAPETINGA": "Glauco Freire",
    "BA OESTE BAHIA": "Glauco Freire",
    "BA SANTA MARIA DA VITORIA": "Glauco Freire",
    "BA TEIXEIRA DE FREITAS": "Glauco Freire",
    "BA VITORIA CONQUISTA": "Glauco Freire",
    "ES ESPIRITO SANTO": "Glauco Freire",
    "ES LINHARES": "Glauco Freire",
    "MG ARACUAI": "Glauco Freire",
    "MG BELO HORIZONTE NORTE": "Glauco Freire",
    "MG CENTRAL DE MINAS": "Glauco Freire",
    "MG GOVERNADOR VALADARES": "Glauco Freire",
    "MG MONTES CLAROS": "Glauco Freire",
    "MG MUCURI": "Glauco Freire",
    "MG NANUQUE": "Glauco Freire",
    "MG POMPEU": "Glauco Freire",
    "MG TEOFILO OTONI": "Glauco Freire",
    "PR BARRACAO": "Marco Antônio Oliveira",
    "PR CAMPO MOURAO": "Marco Antônio Oliveira",
    "PR CANDIDO RONDON": "Marco Antônio Oliveira",
    "PR CORNELIO PROCOPIO": "Marco Antônio Oliveira",
    "PR GUARAPUAVA": "Marco Antônio Oliveira",
    "PR MANGUEIRINHA": "Marco Antônio Oliveira",
    "PR MARINGA": "Marco Antônio Oliveira",
    "PR NOVA LARANJEIRAS": "Marco Antônio Oliveira",
    "PR SAO JOAO": "Marco Antônio Oliveira",
    "RS CACHOEIRA DO SUL": "Marco Antônio Oliveira",
    "RS DOM PEDRITO": "Marco Antônio Oliveira",
    "RS PELOTAS": "Marco Antônio Oliveira",
    "RS PORTO ALEGRE": "Marco Antônio Oliveira",
    "RS SANTIAGO": "Marco Antônio Oliveira",
    "SC CAPINZAL": "Marco Antônio Oliveira",
    "SC SANTA CATARINA CORTE": "Marco Antônio Oliveira",
    "AM MANAUS": "Marcos Longas",
    "GO VALE DO ARAGUAIA": "Marcos Longas",
    "MA ACAILANDIA": "Marcos Longas",
    "MA IMPERATRIZ": "Marcos Longas",
    "MA PRESIDENTE DUTRA": "Marcos Longas",
    "MA SANTA INES": "Marcos Longas",
    "PA ALTAMIRA": "Marcos Longas",
    "PA BELEM": "Marcos Longas",
    "PA JACUNDA": "Marcos Longas",
    "PA MARABA": "Marcos Longas",
    "PA ORIXIMINA": "Marcos Longas",
    "PA PARAGOMINAS": "Marcos Longas",
    "PA XINGU": "Marcos Longas",
    "PA XINGUARA": "Marcos Longas",
    "PR FRANCISCO BELTRAO": "Marcos Longas",
    "PR LONDRINA": "Marcos Longas",
    "RR RORAIMA": "Marcos Longas",
    "SC MARAVILHA": "Marcos Longas",
    "GO OESTE GOIANO": "Rodrigo Rodrigues",
    "MT AGUA BOA": "Rodrigo Rodrigues",
    "MT BARRA DO GARCAS": "Rodrigo Rodrigues",
    "MT CONFRESA": "Rodrigo Rodrigues",
    "MT CUIABA": "Rodrigo Rodrigues",
    "MT JUINA": "Rodrigo Rodrigues",
    "MT MATUPA": "Rodrigo Rodrigues",
    "MT NOVA XAVANTINA": "Rodrigo Rodrigues",
    "MT OESTE MT": "Rodrigo Rodrigues",
    "MT PONTES E LACERDA": "Rodrigo Rodrigues",
    "MT RONDONOPOLIS": "Rodrigo Rodrigues",
    "RO RONDONIA": "Rodrigo Rodrigues",
    "GO GOIAS SUL": "Rodrigo Longo",
    "GO IPORA": "Rodrigo Longo",
    "GO MORRINHOS": "Rodrigo Longo",
    "GO RIO VERDE": "Rodrigo Longo",
    "MG ARAGUARI": "Rodrigo Longo",
    "MG CENTRO OESTE DE MINAS": "Rodrigo Longo",
    "MG GUIMARANIA": "Rodrigo Longo",
    "MG ITUIUTABA": "Rodrigo Longo",
    "MG JOAO PINHEIRO": "Rodrigo Longo",
    "MG LAGOA FORMOSA": "Rodrigo Longo",
    "MG PARACATU": "Rodrigo Longo",
    "MG PATOS DE MINAS": "Rodrigo Longo",
    "MG PATOS NORTE": "Rodrigo Longo",
    "MG PERDIZES": "Rodrigo Longo",
    "MG PONTAL": "Rodrigo Longo",
    "MG SANTA VITORIA": "Rodrigo Longo",
    "MG TIROS": "Rodrigo Longo",
    "MG TRIANGULO": "Rodrigo Longo",
    "MG UBERABA": "Rodrigo Longo",
    "MG UBERLANDIA": "Rodrigo Longo",
    "GO GOIANIA": "Rodrigo Frigoni",
    "GO GOIAS NORTE": "Rodrigo Frigoni",
    "GO MINEIROS": "Rodrigo Frigoni",
    "PA NOVO PROGRESSO": "Rodrigo Frigoni",
    "SP ARACATUBA": "Rodrigo Frigoni",
    "SP BAURU": "Rodrigo Frigoni",
    "Virtual Sales Region": "Rodrigo Frigoni",
    "MG BELO HORIZONTE SUL": "Rodrigo Peixoto",
    "MG BOM SUCESSO": "Rodrigo Peixoto",
    "MG CARMO DO RIO CLARO": "Rodrigo Peixoto",
    "MG CONSELHEIRO LAFAIETE": "Rodrigo Peixoto",
    "MG ITABIRA": "Rodrigo Peixoto",
    "MG ITANHANDU": "Rodrigo Peixoto",
    "MG LAVRAS": "Rodrigo Peixoto",
    "MG POUSO ALEGRE": "Rodrigo Peixoto",
    "MG SAO GONCALO DO SAPUCAI": "Rodrigo Peixoto",
    "MG SAO JOAO DEL REI": "Rodrigo Peixoto",
    "SE SERGIPE": "Rodrigo Peixoto",
    "PR CARAMBEI": "Timótheo Silveira",
    "PR CASTRO": "Timótheo Silveira",
    "RS FREDERICO WESTPHALEN": "Timótheo Silveira",
    "RS IJUI": "Timótheo Silveira",
    "RS SANTA ROSA": "Timótheo Silveira",
    "RS TAPEJARA": "Timótheo Silveira",
    "RS TEUTONIA": "Timótheo Silveira",
    "SC BRACO DO NORTE": "Timótheo Silveira",
    "SC CONCORDIA": "Timótheo Silveira",
    "SC SANTA CATARINA": "Timótheo Silveira",
    "SC TIMBO": "Timótheo Silveira",
    "SC TREZE TILIAS": "Timótheo Silveira"
  }
};
